{
    "terminalFault": [
        {
            "CRT": "03-04",
            "NUB": 29
        },
        {
            "CRT": "03-05",
            "NUB": 33
        },
        {
            "CRT": "03-06",
            "NUB": 1
        },
        {
            "CRT": "03-07",
            "NUB": 0
        },
        {
            "CRT": "03-08",
            "NUB": 0
        },
        {
            "CRT": "03-09",
            "NUB": 0
        },
        {
            "CRT": "03-10",
            "NUB": 0
        },
        {
            "CRT": "03-11",
            "NUB": 0
        },
        {
            "CRT": "03-12",
            "NUB": 0
        },
        {
            "CRT": "03-13",
            "NUB": 0
        },
        {
            "CRT": "03-14",
            "NUB": 0
        },
        {
            "CRT": "03-15",
            "NUB": 0
        },
        {
            "CRT": "03-16",
            "NUB": 0
        },
        {
            "CRT": "03-17",
            "NUB": 0
        },
        {
            "CRT": "03-18",
            "NUB": 0
        },
        {
            "CRT": "03-19",
            "NUB": 0
        },
        {
            "CRT": "03-20",
            "NUB": 0
        },
        {
            "CRT": "03-21",
            "NUB": 0
        },
        {
            "CRT": "03-22",
            "NUB": 0
        },
        {
            "CRT": "03-23",
            "NUB": 0
        },
        {
            "CRT": "03-24",
            "NUB": 0
        },
        {
            "CRT": "03-25",
            "NUB": 0
        },
        {
            "CRT": "03-26",
            "NUB": 0
        },
        {
            "CRT": "03-27",
            "NUB": 0
        },
        {
            "CRT": "03-28",
            "NUB": 0
        },
        {
            "CRT": "03-29",
            "NUB": 0
        },
        {
            "CRT": "03-30",
            "NUB": 0
        },
        {
            "CRT": "03-31",
            "NUB": 0
        },
        {
            "CRT": "04-01",
            "NUB": 0
        },
        {
            "CRT": "04-02",
            "NUB": 0
        }
    ],
    "acquisitionTerminal": [
        {
            "CRT": "03-04",
            "NUB": 118
        },
        {
            "CRT": "03-05",
            "NUB": 106
        },
        {
            "CRT": "03-06",
            "NUB": 24
        },
        {
            "CRT": "03-07",
            "NUB": 0
        },
        {
            "CRT": "03-08",
            "NUB": 0
        },
        {
            "CRT": "03-09",
            "NUB": 0
        },
        {
            "CRT": "03-10",
            "NUB": 0
        },
        {
            "CRT": "03-11",
            "NUB": 0
        },
        {
            "CRT": "03-12",
            "NUB": 0
        },
        {
            "CRT": "03-13",
            "NUB": 0
        },
        {
            "CRT": "03-14",
            "NUB": 0
        },
        {
            "CRT": "03-15",
            "NUB": 0
        },
        {
            "CRT": "03-16",
            "NUB": 0
        },
        {
            "CRT": "03-17",
            "NUB": 0
        },
        {
            "CRT": "03-18",
            "NUB": 0
        },
        {
            "CRT": "03-19",
            "NUB": 0
        },
        {
            "CRT": "03-20",
            "NUB": 0
        },
        {
            "CRT": "03-21",
            "NUB": 0
        },
        {
            "CRT": "03-22",
            "NUB": 0
        },
        {
            "CRT": "03-23",
            "NUB": 0
        },
        {
            "CRT": "03-24",
            "NUB": 0
        },
        {
            "CRT": "03-25",
            "NUB": 0
        },
        {
            "CRT": "03-26",
            "NUB": 0
        },
        {
            "CRT": "03-27",
            "NUB": 0
        },
        {
            "CRT": "03-28",
            "NUB": 0
        },
        {
            "CRT": "03-29",
            "NUB": 0
        },
        {
            "CRT": "03-30",
            "NUB": 0
        },
        {
            "CRT": "03-31",
            "NUB": 0
        },
        {
            "CRT": "04-01",
            "NUB": 0
        },
        {
            "CRT": "04-02",
            "NUB": 0
        }
    ],
    "measuringPoint": [
        {
            "CRT": "03-04",
            "NUB": 3283
        },
        {
            "CRT": "03-05",
            "NUB": 2897
        },
        {
            "CRT": "03-06",
            "NUB": 1100
        },
        {
            "CRT": "03-07",
            "NUB": 0
        },
        {
            "CRT": "03-08",
            "NUB": 0
        },
        {
            "CRT": "03-09",
            "NUB": 0
        },
        {
            "CRT": "03-10",
            "NUB": 0
        },
        {
            "CRT": "03-11",
            "NUB": 0
        },
        {
            "CRT": "03-12",
            "NUB": 0
        },
        {
            "CRT": "03-13",
            "NUB": 0
        },
        {
            "CRT": "03-14",
            "NUB": 0
        },
        {
            "CRT": "03-15",
            "NUB": 0
        },
        {
            "CRT": "03-16",
            "NUB": 0
        },
        {
            "CRT": "03-17",
            "NUB": 0
        },
        {
            "CRT": "03-18",
            "NUB": 0
        },
        {
            "CRT": "03-19",
            "NUB": 0
        },
        {
            "CRT": "03-20",
            "NUB": 0
        },
        {
            "CRT": "03-21",
            "NUB": 0
        },
        {
            "CRT": "03-22",
            "NUB": 0
        },
        {
            "CRT": "03-23",
            "NUB": 0
        },
        {
            "CRT": "03-24",
            "NUB": 0
        },
        {
            "CRT": "03-25",
            "NUB": 0
        },
        {
            "CRT": "03-26",
            "NUB": 0
        },
        {
            "CRT": "03-27",
            "NUB": 0
        },
        {
            "CRT": "03-28",
            "NUB": 0
        },
        {
            "CRT": "03-29",
            "NUB": 0
        },
        {
            "CRT": "03-30",
            "NUB": 0
        },
        {
            "CRT": "03-31",
            "NUB": 0
        },
        {
            "CRT": "04-01",
            "NUB": 0
        },
        {
            "CRT": "04-02",
            "NUB": 0
        }
    ]
}