[
    {
        "CONS_ID": 102000068598,
        "FGB": "5.7",
        "CONS_NAME": "江苏宜兴强制隔离戒毒所",
        "YEARONYEAR": "-"
    },
    {
        "contrast": "上升",
        "CONS_ID": 102000008871,
        "FGB": "5.4",
        "CONS_NAME": "无锡金涛置业发展有限公司",
        "YEARONYEAR": 207
    },
    {
        "CONS_ID": 102000016426,
        "FGB": "4.5",
        "CONS_NAME": "SVIP宜兴市公用产业建设投资有限公司（广汇南路片排涝泵站）",
        "YEARONYEAR": "-"
    },
    {
        "CONS_ID": 102000060990,
        "FGB": "3.7",
        "CONS_NAME": "SVIP太华新四军纪念馆",
        "YEARONYEAR": "-"
    },
    {
        "CONS_ID": 102000068595,
        "FGB": "3.2",
        "CONS_NAME": "宜兴市新源物业管理有限公司",
        "YEARONYEAR": "-"
    },
    {
        "CONS_ID": 102000056643,
        "FGB": "3.0",
        "CONS_NAME": "宜兴市公共建筑建设管理中心（行政服务中心）",
        "YEARONYEAR": "-"
    }
]