[
    {
        "USER_CHECK_COS": 0.9,
        "GLYS_VALUE": 0.3321,
        "CONS_NAME": "宜兴市宜丰合金球铸有限公司"
    },
    {
        "USER_CHECK_COS": 0.9,
        "GLYS_VALUE": 0.7522,
        "CONS_NAME": "宜兴市盛鑫轧辊有限公司"
    },
    {
        "USER_CHECK_COS": 0.9,
        "GLYS_VALUE": 0.8024,
        "CONS_NAME": "宜兴利荣达科技有限公司"
    },
    {
        "USER_CHECK_COS": 0.9,
        "GLYS_VALUE": 0.8881,
        "CONS_NAME": "江苏中超控股股份有限公司（2#变电所T4、T5变)"
    }
]