{
    "resultList": [
        {
            "OUT_LINE_TIME_HOUR": 3,
            "DATA_DATE": "2019/04/02 07:16",
            "CONS_NAME": "潞安卓泰祥和金属科技宜兴有限公司",
            "OUT_LINE_TIME_MIN": 18.516666666666666666666666666666666667
        }
    ]
}