[
    {
        "GZZB": "       71.38",
        "TRAN_NAME": "T1变",
        "ZZZB": "       14.98",
        "CONS_NAME": "宜兴市国昌轧辊有限公司"
    },
    {
        "GZZB": "       41.94",
        "TRAN_NAME": "T1变",
        "ZZZB": "        0.00",
        "CONS_NAME": "SVIP江苏康禄养老产业发展有限公司"
    },
    {
        "GZZB": "       41.05",
        "TRAN_NAME": "T3变",
        "ZZZB": "       20.71",
        "CONS_NAME": "无锡华燕新电源有限公司"
    },
    {
        "GZZB": "       36.76",
        "TRAN_NAME": "T2变",
        "ZZZB": "       12.69",
        "CONS_NAME": "宜兴水务集团有限公司（竹海源水源增压站湖滏水厂）"
    },
    {
        "GZZB": "       27.10",
        "TRAN_NAME": "T4变",
        "ZZZB": "       42.48",
        "CONS_NAME": "无锡华燕新电源有限公司"
    },
    {
        "GZZB": "       13.52",
        "TRAN_NAME": "T1变",
        "ZZZB": "       26.44",
        "CONS_NAME": "宜兴市宏鹏铸钢有限公司"
    }
]