{
    "resultList": [
        {
            "PROCESS": "到达现场已确认",
            "SEND_TIME": "2017-03-31",
            "CODE_NAME": "抢修工单",
            "USERNAME": "管理员",
            "CONS_NAME": "SVIP无锡工艺职业技术学院(新校区)",
            "WN_NO": "25278"
        },
        {
            "PROCESS": "派发",
            "SEND_TIME": "2019-03-21",
            "CODE_NAME": "抢修工单",
            "USERNAME": "test",
            "CONS_NAME": "江苏中超控股股份有限公司（2#变电所T4、T5变)",
            "WN_NO": "1241681"
        },
        {
            "PROCESS": "派发",
            "SEND_TIME": "2019-03-21",
            "CODE_NAME": "抢修工单",
            "USERNAME": "test",
            "CONS_NAME": "江苏中超控股股份有限公司（2#变电所T4、T5变)",
            "WN_NO": "1241685"
        },
        {
            "PROCESS": "派发",
            "SEND_TIME": "2019-03-22",
            "CODE_NAME": "抢修工单",
            "USERNAME": "test",
            "CONS_NAME": "SVIP无锡工艺职业技术学院（老校区）",
            "WN_NO": "1241703"
        },
        {
            "PROCESS": "派发",
            "SEND_TIME": "2019-03-25",
            "CODE_NAME": "抢修工单",
            "USERNAME": "test",
            "CONS_NAME": "江苏中辰电缆有限公司（新厂区）",
            "WN_NO": "1241725"
        },
        {
            "PROCESS": "派发",
            "SEND_TIME": "2019-03-25",
            "CODE_NAME": "抢修工单",
            "USERNAME": "test",
            "CONS_NAME": "江苏中辰电缆有限公司（新厂区）",
            "WN_NO": "1241723"
        },
        {
            "PROCESS": "故障已确认",
            "SEND_TIME": "2019-03-19",
            "CODE_NAME": "抢修工单",
            "USERNAME": "test",
            "CONS_NAME": "江苏中辰电缆有限公司（新厂区）",
            "WN_NO": "1241641"
        },
        {
            "PROCESS": "派发",
            "SEND_TIME": "2019-03-25",
            "CODE_NAME": "抢修工单",
            "USERNAME": "test",
            "CONS_NAME": "江苏中辰电缆有限公司（新厂区）",
            "WN_NO": "1241727"
        },
        {
            "PROCESS": "派发",
            "SEND_TIME": "2019-03-21",
            "CODE_NAME": "抢修工单",
            "USERNAME": "test",
            "CONS_NAME": "江苏中辰电缆有限公司（新厂区）",
            "WN_NO": "1241683"
        },
        {
            "PROCESS": "抢修已确认",
            "SEND_TIME": "2019-03-19",
            "CODE_NAME": "抢修工单",
            "USERNAME": "test",
            "CONS_NAME": "江苏中辰电缆有限公司（新厂区）",
            "WN_NO": "1241637"
        },
        {
            "PROCESS": "抢修已确认",
            "SEND_TIME": "2017-03-30",
            "CODE_NAME": "抢修工单",
            "USERNAME": "宜能实业监控中心",
            "CONS_NAME": "SVIP无锡工艺职业技术学院(新校区)",
            "WN_NO": "25242"
        },
        {
            "PROCESS": "已接单",
            "SEND_TIME": "2017-03-30",
            "CODE_NAME": "抢修工单",
            "USERNAME": "",
            "CONS_NAME": "SVIP无锡工艺职业技术学院(新校区)",
            "WN_NO": "25262"
        }
    ]
}